# Generated by Django 5.1.1 on 2024-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.IntegerField()),
                ('course_name', models.CharField(max_length=50)),
                ('course_fee', models.BigIntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('trainer_name', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
    ]
